[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.6.3",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "openai>=1.106.1",
    "python-dotenv>=1.1.1",
]
